[package]
name = "microrhythm"
version = "0.1.0"
authors = ["Alex Loomis"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
insta = "1.7.1"

